config/routes.rb
Rails.application.routes.draw do


  root :to => 'page#index'

  get 'login', :to => "login#index"
  post 'login/login'
  get 'login/login', :to => "login#index"
  get 'login/logout'
  get 'login/register'
  resources :permissions
  resources :user_groups
  resources :users
  get 'articles/:id/blocks', :to => "articles#blocks"
  post 'articles/save_blocks', :to => "articles#save_blocks"
  resources :articles, :except => [:index]
  get 'articles', to: redirect("/")
  resources :article_categories
  resources :sites
  get 'sites/:id/assets', :to => "sites#assets"
  post 'sites/save_assets', :to => "sites#save_assets"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  has_many :article_blocks

  scope :by_recently_updated, lambda { order("updated_at DESC")}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy,:blocks]
  before_action :check_permissions, only: [:new, :edit, :blocks]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @author = User.find(@article.author)
    @last_author = User.find(@article.author)
  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = ArticleCategory.all
  end

  # GET /articles/1/edit
  def edit
    @categories = ArticleCategory.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @categories = ArticleCategory.all
    @category = ArticleCategory.find(article_params[:article_category_id])
    respond_to do |format|
      if @article.save
        format.html { redirect_to "/articles/"+@article.id.to_s+"/blocks", notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @categories = ArticleCategory.all
    @category = ArticleCategory.find(article_params[:article_category_id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to "/articles/"+@article.id.to_s+"/blocks", notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def blocks
    @current_user = current_user
  end
  
  def save_blocks
    @i = 0
    @article = Article.find(params[:article_id])
    @article.article_blocks.each do |block|
      block.destroy
    end

    params['blocks'].each_with_index do |block,index|
      @article_block = ArticleBlock.new(
        :block_type => block["block_type"],
        :display => block["display"],
        :content => block["content"],
        :order => block["order"],
        :author => block["author"],
        :last_edited_author => block["last_edited_author"],
        :article_id => block["article_id"]
      )
      @article_block.save
    end
    redirect_to(@article)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :author, :last_edited_author, :article_category_id)
    end

    def check_permissions
      unless current_user && current_user.can("add_articles")
        flash[:notice] = "You must login to add an Article"
        redirect_to(login_path)
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
  <%= f.hidden_field :author, {:value=>current_user.id} %>
  <% end %>
  <%= f.hidden_field :last_edited_author, {:value=>current_user.id} %>
  
  <div class="field">
    <%= f.label :name, :class=>"form-label" %>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :article_category_id %>
    <%= f.select(:article_category_id, @categories.where(:site_id=>current_site.id).map{|category| [category.name, category.id]}, {}, {:class=>"form-control"}) %>
  </div>

  <div class="actions">
    <%= f.submit :class=>"bttn primary" %>
  </div>
<% end %>

app/views/articles/blocks.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Code Blocks to <%=@article.name%></h1>


<div class="page-menu">
  <div class="bttn-group">
    <a href="#" class="bttn primary dropdown" data-buttton-dropdown="code-blocks">
      Add Code Block <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu" id="code-blocks">
      <li><a href="#" data-add-block="html">HTML</a></li>
      <li><a href="#" data-add-block="javascript">Javascript</a></li>
      <li><a href="#" data-add-block="css">CSS</a></li>
    </ul>
  </div>
  <a href="#" data-add-block="content" class="bttn primary">Add Content Block</a>
  <!--<a href="#" class="bttn float-right">Add Header Assets</a>-->
</div>

  <%= form_tag articles_save_blocks_path %>
    <input type="hidden" name="article_id" value="<%=params[:id]%>">
    <div id="article-blocks-container">
      <% @article.article_blocks.each_with_index do |block, index| %>
        <div class="article-block" id="article-block-<%=index%>" data-block-type="<%=block.block_type%>" data-editable="true">
          <div class="article-block-heading">
            <i class="fa fa-arrows"></i>
            <h3><%=block.block_type_name%> Block</h3>
            <% unless block.block_type == "content" %>
            <label class="checkbox">
              <%= hidden_field_tag "blocks[][display]" %>
              <%= check_box_tag "blocks[][display]", 1, block.display %>
              For Display
            </label>
            <% end %>
            <span class="bttn danger small" data-delete-block="<%=index%>">Delete</span>
          </div>
          <div class="article-block-body">
            <div id="editor-<%=index.to_s%>-wrap" class="editor-wrap">
              <% if block.block_type == "content" %>
                <textarea name="blocks[][content]" id="textarea-<%=index%>" class="content-editor"><%= block.content %></textarea>
              <% else %>
                <div class="ace-editor" id="editor-<%=index%>"><%= block.content %></div>
                <textarea name="blocks[][content]" id="textarea-<%=index%>" class="hide"></textarea>
              <% end %>
            </div>
          </div>
          <% if block.block_type == "content" %>
              <%= hidden_field_tag "blocks[][display]" %>
          <% end %>
          <input type="hidden" name="blocks[][article_id]" value="<%=params[:id]%>">
          <input type="hidden" name="blocks[][block_type]" value="<%=block.block_type%>">
          <input type="hidden" name="blocks[][order]" class="block-order" value="">
          <input type="hidden" name="blocks[][author]" value="<%=block.author%>">
          <input type="hidden" name="blocks[][last_edited_author]" value="<%=@current_user.id%>">
        </div>
      <% end %>
    </div>
    
    <div class="article-blocks-actions clearfix">
      <button class="bttn primary float-right hide bttn-save-blocks">Save</button>
    </div>
  </form>

  <script type="text/x-template" id="code-block-template">
    <div class="article-block" id="article-block-{{idNumber}}">
      <div class="article-block-heading">
        <i class="fa fa-arrows"></i>
        <h3>{{blockName}}</h3>
        <label class="checkbox">
          <input type="hidden" name="blocks[][display]">
          <input type="checkbox" name="blocks[][display]">
          For Display
        </label>
        <span class="bttn danger small" data-delete-block="{{idNumber}}">Delete</span>
      </div>
      <div class="article-block-body">
        <div id="editor-{{idNumber}}-wrap" class="editor-wrap">
          <div class="ace-editor" id="editor-{{idNumber}}"></div>
          <textarea name="blocks[][content]" id="textarea-{{idNumber}}" class="hide"></textarea>
        </div>
      </div>
      <input type="hidden" name="blocks[][article_id]" value="<%=params[:id]%>">
      <input type="hidden" name="blocks[][block_type]" value="{{blockType}}">
      <input type="hidden" name="blocks[][order]" class="block-order" value="">
      <input type="hidden" name="blocks[][author]" value="<%=@current_user.id%>">
      <input type="hidden" name="blocks[][last_edited_author]" value="<%=@current_user.id%>">
    </div>
  </script>

  <script type="text/x-template" id="content-block-template">
    <div class="article-block" id="article-block-{{idNumber}}">
      <div class="article-block-heading">
        <i class="fa fa-arrows"></i>
        <h3>{{blockName}}</h3>
        <span class="bttn danger small" data-delete-block="{{idNumber}}">Delete</span>
      </div>
      <div class="article-block-body">
        <textarea name="blocks[][content]" id="textarea-{{idNumber}}" class="content-editor"></textarea>
      </div>
      <input type="hidden" name="blocks[][display]">
      <input type="hidden" name="blocks[][article_id]" value="<%=params[:id]%>">
      <input type="hidden" name="blocks[][block_type]" value="{{blockType}}">
      <input type="hidden" name="blocks[][order]" class="block-order" value="">
      <input type="hidden" name="blocks[][author]" value="<%=@current_user.id%>">
      <input type="hidden" name="blocks[][last_edited_author]" value="<%=@current_user.id%>">
    </div>
  </script>

</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Last edited author</th>
      <th>Article category</th>
      <th>Site</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.name, article_path(article) %></td>
        <td><%= User.find(article.author).get_short_name %></td>
        <td><%= User.find(article.author).get_short_name %></td>
        <td><%= article.article_category.name %></td>
        <td><%= article.article_category.site.name %></td>
        <td>
          <%= link_to 'Edit', edit_article_path(article), :class=>"bttn small" %>
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"bttn danger small" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Article', new_article_path, :class=>"bttn primary" %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="article-info">
  <%=@article.name%>
</h1>

<div class="article-heading clearfix">
  <div class="article-info">
    <span class="key">
      Category
    </span>
    <span class="value">
      <%= link_to @article.article_category.name, @article.article_category %>
    </span>
  </div>
  <div class="article-info">
    <span class="key">
      Written By
    </span>
    <span class="value">
      <%=@author.get_short_name %>
    </span>
  </div>
  <div class="article-info">
    <span class="key">
      Last Updated By
    </span>
    <span class="value">
      <%=@last_author.get_short_name %>
    </span>
  </div>
  <div class="article-info article-actions">
    <a href="<%=edit_article_path(@article)%>" class="bttn">Edit</a>
    <a href="" class="bttn danger">Delete</a>
  </div>
</div>

<div class="article-blocks">

  <% @article.article_blocks.each_with_index do |block, index| %>

    <div class="article-block" data-block-type="<%=block.block_type%>" data-display="<%=block.display%>">
      <% if !block.display && block.block_type != "content"  %>
      <div class="ace-editor" id="editor-<%=index%>"><%= block.content %></div>
      <% else %>
      <%= raw(block.content) %>
      <% end %>
    </div>

  <% end %>

</div>