config/routes.rb
Rails.application.routes.draw do


  root :to => 'page#index'

  get 'login', :to => "login#index"
  post 'login/login'
  get 'login/login', :to => "login#index"
  get 'login/logout'
  get 'login/register'
  resources :permissions
  resources :user_groups
  resources :users
  get 'articles/:id/blocks', :to => "articles#blocks"
  post 'articles/save_blocks', :to => "articles#save_blocks"
  resources :articles, :except => [:index]
  get 'articles', to: redirect("/")
  resources :article_categories
  resources :sites
  get 'sites/:id/assets', :to => "sites#assets"
  post 'sites/save_assets', :to => "sites#save_assets"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions

  scope :sorted, lambda { order("name ASC")}
  scope :newest_fist, lambda { order("created_at DESC")}
  scope :search, lambda { |query| where(["name LIKE ?", "%#{query}"])}

  validates :name,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]
  before_action :check_permissions

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name)
    end

    def check_permissions
      unless current_user && current_user.can("manage_user_groups")
        flash[:notice] = "You must login to view this Page"
        redirect_to(login_path)
      end
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(user_group) do |f| %>
  <% if user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :class=>"form-label" %>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>

  <div class="actions">
    <%= link_to 'Back', user_groups_path, :class=>"bttn" %>
    <%= f.submit :class => "bttn primary" %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form', user_group: @user_group %>

<%= link_to 'Show', @user_group %> |

app/views/user_groups/index.html.erb
<h1>User Groups</h1>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_groups.each do |user_group| %>
      <tr>
        <td><%= user_group.name %></td>
        <td>
          <%= link_to 'Show', user_group, :class=> "bttn small" %>
          <%= link_to 'Edit', edit_user_group_path(user_group), :class=> "bttn small" %>
          <%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "bttn small danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New User Group', new_user_group_path, :class=> "bttn primary" %>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= render 'form', user_group: @user_group %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_group.name %>
</p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>