config/routes.rb
Rails.application.routes.draw do


  root :to => 'page#index'

  get 'login', :to => "login#index"
  post 'login/login'
  get 'login/login', :to => "login#index"
  get 'login/logout'
  get 'login/register'
  resources :permissions
  resources :user_groups
  resources :users
  get 'articles/:id/blocks', :to => "articles#blocks"
  post 'articles/save_blocks', :to => "articles#save_blocks"
  resources :articles, :except => [:index]
  get 'articles', to: redirect("/")
  resources :article_categories
  resources :sites
  get 'sites/:id/assets', :to => "sites#assets"
  post 'sites/save_assets', :to => "sites#save_assets"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  has_many :article_blocks

  scope :by_recently_updated, lambda { order("updated_at DESC")}
end

app/models/article_block.rb
class ArticleBlock < ApplicationRecord
  belongs_to :article

  def block_type_name
    text = self.block_type
    if text=="html"
      return "HTML"
    elsif text=="javascript"
      return "Javascript"
    elsif text=="css"
      return "CSS"
    elsif text=="content"
      return "Content"
    end
    return text
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :site
  has_many :articles
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/permission.rb
class Permission < ApplicationRecord
  
  has_and_belongs_to_many :user_groups
  
  validates :name,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true
  validates :handle,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true          

  def has_permission(user)
    @user_has_permission = false
    @intersection = self.user_groups.all & user.user_groups.all
    return !@intersection.empty?
  end
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :article_categories
  has_many :site_assets
end

app/models/site_asset.rb
class SiteAsset < ApplicationRecord
  belongs_to :site
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_and_belongs_to_many :user_groups

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name,
            :presence => true,
            :length => { :maximum => 25 }
  validates :last_name,
            :presence => true,
            :length => { :maximum => 50 }
  validates :email,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true,
            :format => { :with => EMAIL_REGEX },
            :confirmation => true

  def get_full_name
    "#{first_name} #{last_name}"
  end

  def get_short_name
    "#{first_name} #{last_name.chars.first}."
  end

  def can(permission_handle)
    Permission.find_by(:handle => permission_handle).has_permission(self)
  end

  def has_admin_access?
    self.can("manage_sites") ||
    self.can("manage_users") ||
    self.can("manage_user_groups") ||
    self.can("manage_permissions")
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions

  scope :sorted, lambda { order("name ASC")}
  scope :newest_fist, lambda { order("created_at DESC")}
  scope :search, lambda { |query| where(["name LIKE ?", "%#{query}"])}

  validates :name,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true

end

app/controllers/article_categories_controller.rb
class ArticleCategoriesController < ApplicationController
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]
  before_action :check_add_permissions, only: [:new, :create, :edit, :update]
  before_action :check_delete_permissions, only: [:destroy]

  # GET /article_categories
  # GET /article_categories.json
  def index
    @article_categories = ArticleCategory.all
  end

  # GET /article_categories/1
  # GET /article_categories/1.json
  def show
  end

  # GET /article_categories/new
  def new
    @article_category = ArticleCategory.new
    @sites = Site.all
  end

  # GET /article_categories/1/edit
  def edit
    @sites = Site.all
  end

  # POST /article_categories
  # POST /article_categories.json
  def create
    @article_category = ArticleCategory.new(article_category_params)
    @sites = Site.all
    respond_to do |format|
      if @article_category.save
        format.html { redirect_to @article_category, notice: 'Article category was successfully created.' }
        format.json { render :show, status: :created, location: @article_category }
      else
        format.html { render :new }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_categories/1
  # PATCH/PUT /article_categories/1.json
  def update
    @sites = Site.all
    respond_to do |format|
      if @article_category.update(article_category_params)
        format.html { redirect_to @article_category, notice: 'Article category was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_category }
      else
        format.html { render :edit }
        format.json { render json: @article_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_categories/1
  # DELETE /article_categories/1.json
  def destroy
    @article_category.destroy
    respond_to do |format|
      format.html { redirect_to article_categories_url, notice: 'Article category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_category
      @article_category = ArticleCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_category_params
      params.require(:article_category).permit(:name, :handle, :site_id)
    end

    def check_add_permissions
      unless current_user && current_user.can("add_articles")
        flash[:notice] = "You must login to Add Categories"
        redirect_to(login_path)
      end
    end

    def check_delete_permissions
      unless current_user && current_user.can("delete_articles")
        flash[:notice] = "You must login to Delete Categories"
        redirect_to(login_path)
      end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def login
    if params[:email].present? && params[:password].present?
      found_user = User.where(:email => params[:email]).first
      if found_user
        if found_user.active
          authorized_user = found_user.authenticate(params[:password])
        else
          flash[:notice] = "This user account isn't active yet."
          render('index')
          return false
        end
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "you are now logged in."
      redirect_to('/')
    else
      flash.now[:notice] = "Invalid username/password combination."
      render('index')
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "You are now logged out"
    redirect_to('/')
  end

  def register
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_categories_helper.rb
module ArticleCategoriesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/article_categories/_form.html.erb
<%= form_for(article_category) do |f| %>
  <% if article_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_category.errors.count, "error") %> prohibited this article_category from being saved:</h2>

      <ul>
      <% article_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :class=>"form-label" %>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :site_id, :class=>"form-label" %>
    <%= f.select(:site_id, @sites.map{|site| [site.name, site.id]}, {:selected=> current_site.id}, {:class=>"form-control"}) %>
  </div>

  <div class="actions">
    <%= f.submit :class=> "bttn primary" %>
    <%= link_to 'Back', article_categories_path, :class=>"bttn" %>
  </div>
<% end %>

app/views/article_categories/edit.html.erb
<h1>Editing Article Category</h1>

<%= render 'form', article_category: @article_category %>

app/views/article_categories/index.html.erb
<h1><%=current_site.name%> Article Categories</h1>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Site</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @article_categories.where(:site => current_site).each do |article_category| %>
      <tr>
        <td><%= article_category.name %></td>
        <td><%= article_category.site.name %></td>
        <td>
          <% if current_user && current_user.can("create_categories") %>
          <%= link_to 'Edit', edit_article_category_path(article_category), :class=>"bttn small" %>
          <% end %>
          <% if current_user && current_user.can("remove_categories") %>
          <%= link_to 'Destroy', article_category, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"bttn small danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_article_category_path, :class=>"bttn primary" %>

app/views/article_categories/new.html.erb
<h1>New Article Category</h1>

<%= render 'form', article_category: @article_category %>

app/views/article_categories/show.html.erb
<h1><%= @article_category.name%></h1>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Article</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @article_category.articles.each do |article|%>
    <tr>
      <td><%= link_to article.name, article_path(article) %></td>
      <td>
        <%= link_to 'Edit', edit_article_path(article), :class=> "bttn small" %>
        <% if current_user && current_user.can("delete_articles") %>
        <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "bttn small danger" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>