config/routes.rb
Rails.application.routes.draw do


  root :to => 'page#index'

  get 'login', :to => "login#index"
  post 'login/login'
  get 'login/login', :to => "login#index"
  get 'login/logout'
  get 'login/register'
  resources :permissions
  resources :user_groups
  resources :users
  get 'articles/:id/blocks', :to => "articles#blocks"
  post 'articles/save_blocks', :to => "articles#save_blocks"
  resources :articles, :except => [:index]
  get 'articles', to: redirect("/")
  resources :article_categories
  resources :sites
  get 'sites/:id/assets', :to => "sites#assets"
  post 'sites/save_assets', :to => "sites#save_assets"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :article_category
  has_many :article_blocks

  scope :by_recently_updated, lambda { order("updated_at DESC")}
end

app/models/article_block.rb
class ArticleBlock < ApplicationRecord
  belongs_to :article

  def block_type_name
    text = self.block_type
    if text=="html"
      return "HTML"
    elsif text=="javascript"
      return "Javascript"
    elsif text=="css"
      return "CSS"
    elsif text=="content"
      return "Content"
    end
    return text
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :site
  has_many :articles
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/permission.rb
class Permission < ApplicationRecord
  
  has_and_belongs_to_many :user_groups
  
  validates :name,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true
  validates :handle,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true          

  def has_permission(user)
    @user_has_permission = false
    @intersection = self.user_groups.all & user.user_groups.all
    return !@intersection.empty?
  end
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :article_categories
  has_many :site_assets
end

app/models/site_asset.rb
class SiteAsset < ApplicationRecord
  belongs_to :site
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_and_belongs_to_many :user_groups

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :first_name,
            :presence => true,
            :length => { :maximum => 25 }
  validates :last_name,
            :presence => true,
            :length => { :maximum => 50 }
  validates :email,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true,
            :format => { :with => EMAIL_REGEX },
            :confirmation => true

  def get_full_name
    "#{first_name} #{last_name}"
  end

  def get_short_name
    "#{first_name} #{last_name.chars.first}."
  end

  def can(permission_handle)
    Permission.find_by(:handle => permission_handle).has_permission(self)
  end

  def has_admin_access?
    self.can("manage_sites") ||
    self.can("manage_users") ||
    self.can("manage_user_groups") ||
    self.can("manage_permissions")
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions

  scope :sorted, lambda { order("name ASC")}
  scope :newest_fist, lambda { order("created_at DESC")}
  scope :search, lambda { |query| where(["name LIKE ?", "%#{query}"])}

  validates :name,
            :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeWiki</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <% current_site.site_assets.each do |site_asset| %>
      <% if File.extname(site_asset.asset_url) == ".css" %>
        <link href="<%= URI::parse(site_asset.asset_url).path %>" rel="stylesheet">
      <% end %>
    <% end %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  </head>

  <body>

    <header id="global-sidebar">

      <div id="site-selector">
        <label class="form-label" for="site-selector-field">
          View Styles for Site:
        </label>
        <select id="site-selector-field" class="form-control">
          <% for site in Site.all %>
          <option value="<%=site.id%>" <%if current_site.id == site.id%>selected<%end%>><%=site.name%></option>
          <% end %>
        </select>
      </div>

      <nav id="main-nav">
        <span class="nav-title">
          Categories
        </span>
        <ul class="nav">
          <% ArticleCategory.where(:site => current_site).each do |category| %>
          <li>
            <%= link_to "#{category.name} (#{category.articles.count})", category %>
          </li>
          <% end %>
        </ul>

        <input type="text" class="form-control dark" id="input-search-articles" placeholder="search for articles" />

      </nav>

      <div class="site-actions">
        <a href="<%= new_article_path %>" class="bttn primary">
          Add Article
        </a>
        <a href="<%= article_categories_path %>" class="bttn">
          Categories
        </a>
      </div>

      <% if current_user && current_user.has_admin_access? %>
      <nav id="site-nav">
        <span class="nav-title">
          Admin
        </span>
        <ul class="nav">
          <% if current_user.can("manage_sites")%>
          <li><a href="<%=sites_path %>">Manage Sites</a></li>
          <% end %>
          <% if current_user.can("manage_users")%>
          <li><a href="<%=users_path %>">Manage Users</a></li>
          <% end %>
          <% if current_user.can("manage_user_groups")%>
          <li><a href="<%=user_groups_path %>">Manage User Groups</a></li>
          <% end %>
          <% if current_user.can("manage_permissions")%>
          <li><a href="<%= permissions_path%>">Manage Permissions</a></li>
          <% end %>
        </ul>
      </nav>
      <% end %>

    </header>

    <div id="panel-results" class="panel">
      <h1>Results</h1>
      <ul id="search-results">
        <li>Not finding anything...</li>
      </ul>
      <a href="#" class="bttn" data-close-panel="panel-results">
        Close
      </a>
    </div>

    <div id="top-links">
      <span class="link-group updates-link">
        <%= link_to "View Latest Updates", root_path %>
      </span>
      <span class="link-group logged-in-label">
        <% if current_user %>
        Logged in as <strong><%= current_user.get_short_name %></strong>
        <a href="<%=login_logout_path%>" class="btn-logout">Logout</a>
        <% else %>
          <a href="<%= login_path %>">Login</a>
        <% end %>
      </span>
    </div>

    <div id="main-shell">
      <%= yield %>
    </div>
    <script src="//use.fontawesome.com/f8efffc434.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/mode-coldfusion.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/mode-javascript.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/mode-sass.js"></script>
    <% current_site.site_assets.each do |site_asset| %>
      <% if File.extname(site_asset.asset_url) == ".js" %>
          <script src="<%= URI::parse(site_asset.asset_url).path %>"></script>
      <% end %>
  <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Code Wiki</h1>

<% if !flash[:notice].blank? %>
    <div id="notice">
      <%= flash[:notice] %>
    </div>
<% end %>

<h2>Latest Updates</h2>
<ul class="update-list">
<% for article in Article.by_recently_updated.first(5) %>
  <li>
    <% if article.created_at == article.updated_at %>
      <span class="action-performed">Article Created</span>
    <% else %>
      <span class="action-performed">Article Updated</span>
    <% end %>
    <div class="status-update">
      <%= link_to article.name, article%> was
      <% if article.created_at == article.updated_at %>
        <strong>created</strong> by <%= User.find(article.author).get_full_name %>
      <% else %>
        <strong>updated</strong> <%= User.find(article.last_edited_author).get_full_name %>
      <% end %>
    </div>
    <time datetime="<%= article.updated_at.strftime("%Y-%d-%m") %>">
      <%= article.updated_at.strftime("%B %d, %Y") %>
    </time>
  </li>
<% end %>
</ul>